language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t Udacity-monolith-to-microservices-project .
  - docker tag Udacity-monolith-to-microservices-project YOUR_DOCKER_HUB/Udacity-monolith-to-microservices-project:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/Udacity-monolith-to-microservices-project
